trigger:
- main
# Trigger pipeline on main branch changes

pool:
  name: default # Use the default agent pool

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

steps:
  - script: |
      echo "Disabling SSL Verification for .NET SDK Installation"
      export DOTNET_CLI_HOME=/tmp
      export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
      export NODE_TLS_REJECT_UNAUTHORIZED=0
    displayName: 'Disable SSL Verification'

  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x.x'  # Replace with required version

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Web Projects'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'dot-service connection'
      appType: 'webAppLinux'
      appName: 'dot-webapp'
      package: '$(Build.ArtifactStagingDirectory)/*/.zip'